version: '3.8'
services:
  frontend:
    container_name: vpwa_frontend
    restart: unless-stopped
    build: https://github.com/VPWA-project/VPWA_frontend.git#main
    ports:
      - "8080:8080"
    depends_on:
      - backend
  backend:
    container_name: vpwa_backend
    restart: unless-stopped
    build: https://github.com/VPWA-project/VPWA_backend.git#main
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    env_file:
      - ./backend/.env
  postgres:
    image: "postgres:latest"
    container_name: vpwa_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vpwa
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
    db-data: